#!/bin/bash
#
# Generate HTML documentation for the project using Epydoc
#

# TODO: start using Sphinx

rm -rf doc/*
epydoc --html --output doc/ --name "Python-OpenID" --top openid \
    --url "http://openidenabled.com/python-openid/" --inheritance listed \
    --no-private -v \
    $( find openid -name '*.py' -and -not -path 'openid/test*' )
